name: video_thumbnail_custom
description: A flutter plugin for creating a thumbnail from a local video file or from a video URL.
version: 0.5.5

homepage: https://github.com/justsoft
repository: https://github.com/justsoft/video_thumbnail
issue_tracker: https://github.com/justsoft/video_thumbnail/issues

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: '>=3.10.0'

dependencies:
  flutter:
    sdk: flutter
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: xyz.justsoft.video_thumbnail_custom
        pluginClass: VideoThumbnailCustomPlugin
      ios:
        pluginClass: VideoThumbnailCustomPlugin
        fileName: video_thumbnail_custom.podspec
